[package]
org = "ballerina"
name = "mqtt"
version = "1.1.0"
authors = ["ballerina"]
keywords = ["mqtt", "client", "messaging", "network", "pubsub", "iot"]
repository = "https://github.com/ballerina-platform/module-ballerina-mqtt"
distribution = "2201.9.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mqtt-native"
version = "1.1.0"
path = "../native/build/libs/mqtt-native-1.1.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "org.eclipse.paho"
artifactId = "org.eclipse.paho.mqttv5.client"
version = "1.2.5"
path = "./lib/org.eclipse.paho.mqttv5.client-1.2.5.jar"

[[platform.java17.dependency]]
groupId = "org.bouncycastle"
artifactId = "bcpkix-jdk18on"
version = "1.77"
path = "./lib/bcpkix-jdk18on-1.77.jar"

[[platform.java17.dependency]]
groupId = "org.bouncycastle"
artifactId = "bcutil-jdk18on"
version = "@bouncycastle.version@"
path = "./lib/bcutil-jdk18on-@bouncycastle.version@.jar"
